"use client";

import React, { useState } from "react";
import {
  Calendar,
  Clock,
  CheckCircle2,
  Circle,
  Sparkles,
  Sun,
  Sunset,
  Moon,
  Zap,
  RotateCcw,
  Plus,
  ExternalLink
} from "lucide-react";
import { Task } from "@/lib/student-types";

interface DailyPlannerViewProps {
  tasks: Task[];
  onToggleTask: (id: string) => void;
  isDarkMode: boolean;
  onNavigateToTab: (tab: any) => void;
}

export function DailyPlannerView({
  tasks,
  onToggleTask,
  isDarkMode,
  onNavigateToTab
}: DailyPlannerViewProps) {
  const slots: ('Morning' | 'Afternoon' | 'Evening' | 'Night')[] = ['Morning', 'Afternoon', 'Evening', 'Night'];

  const getSlotIcon = (slot: string) => {
    switch (slot) {
      case 'Morning': return <Sun className="w-5 h-5 text-amber-400" />;
      case 'Afternoon': return <Sun className="w-5 h-5 text-orange-400" />;
      case 'Evening': return <Sunset className="w-5 h-5 text-purple-400" />;
      case 'Night': return <Moon className="w-5 h-5 text-indigo-400" />;
      default: return <Clock className="w-5 h-5 text-cyan-400" />;
    }
  };

  const getSlotTimeRange = (slot: string) => {
    switch (slot) {
      case 'Morning': return '7:00 AM – 12:00 PM';
      case 'Afternoon': return '12:00 PM – 5:00 PM';
      case 'Evening': return '5:00 PM – 9:00 PM';
      case 'Night': return '9:00 PM – 12:00 AM';
      default: return '';
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Header Banner */}
      <div className={`p-6 rounded-3xl border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 ${
        isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
      }`}>
        <div className="flex items-center space-x-3">
          <div className="p-3 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-500 text-white shadow-lg">
            <Calendar className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-black text-white">Adaptive Daily Timetable</h2>
            <p className="text-xs text-slate-400">
              Generated by Scheduler Agent &bull; Auto-balances study slots and active recall
            </p>
          </div>
        </div>

        <button
          onClick={() => onNavigateToTab("workspace")}
          className="px-4 py-2 rounded-xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 font-extrabold text-xs flex items-center space-x-1.5 hover:bg-cyan-500/20 transition-all"
        >
          <Zap className="w-4 h-4 text-cyan-400" />
          <span>Auto-Replan Schedule with AI</span>
        </button>
      </div>

      {/* Time Blocked Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {slots.map((slot) => {
          const slotTasks = tasks.filter(t => t.timeSlot === slot);
          return (
            <div
              key={slot}
              className={`p-6 rounded-3xl border space-y-4 ${
                isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
              }`}
            >
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center space-x-2.5">
                  <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">
                    {getSlotIcon(slot)}
                  </div>
                  <div>
                    <h3 className="font-extrabold text-base text-white">{slot} Block</h3>
                    <p className="text-[11px] text-slate-400">{getSlotTimeRange(slot)}</p>
                  </div>
                </div>
                <span className="text-xs font-bold text-slate-400">
                  {slotTasks.filter(t => t.completed).length} / {slotTasks.length} Done
                </span>
              </div>

              {/* Task Cards */}
              <div className="space-y-3">
                {slotTasks.length === 0 ? (
                  <p className="text-xs text-slate-500 italic py-4 text-center">No tasks assigned for this time block.</p>
                ) : (
                  slotTasks.map((t) => (
                    <div
                      key={t.id}
                      className={`p-4 rounded-2xl border transition-all flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 ${
                        t.completed
                          ? "bg-slate-950/60 border-slate-800 text-slate-500 opacity-70"
                          : "bg-slate-800/40 border-slate-700/60 hover:border-cyan-500/50 text-slate-100"
                      }`}
                    >
                      <div
                        onClick={() => onToggleTask(t.id)}
                        className="flex items-start space-x-3 cursor-pointer flex-1"
                      >
                        <button className="text-cyan-400 mt-0.5">
                          {t.completed ? (
                            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                          ) : (
                            <Circle className="w-5 h-5 text-slate-500" />
                          )}
                        </button>
                        <div>
                          <h4 className={`text-xs sm:text-sm font-bold ${t.completed ? 'line-through text-slate-500' : 'text-white'}`}>
                            {t.title}
                          </h4>
                          <p className="text-[11px] text-slate-400 mt-0.5 flex flex-wrap items-center gap-1.5">
                            <span>{t.subject} &bull; {t.durationMinutes} mins</span>
                            {t.sourceAgent && (
                              <span className="px-1.5 py-0.2 rounded bg-cyan-500/10 text-cyan-300 text-[10px] font-bold border border-cyan-500/20">
                                {t.sourceAgent}
                              </span>
                            )}
                          </p>
                        </div>
                      </div>

                      <div className="flex items-center space-x-2 w-full sm:w-auto justify-between sm:justify-end border-t sm:border-t-0 border-slate-800 pt-2 sm:pt-0">
                        {t.platformUrl && (
                          <a
                            href={t.platformUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                            className="px-2 py-1 rounded-lg bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 text-[10px] font-bold border border-cyan-500/30 flex items-center space-x-1"
                          >
                            <span>{t.platformName || "Open"}</span>
                            <ExternalLink className="w-3 h-3" />
                          </a>
                        )}

                        <span className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                          t.priority === 'High'
                            ? 'bg-rose-500/20 text-rose-300'
                            : 'bg-blue-500/20 text-blue-300'
                        }`}>
                          {t.priority}
                        </span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          );
        })}
      </div>

    </div>
  );
}
