"use client";

import React, { useState } from "react";
import {
  BarChart3,
  TrendingUp,
  Brain,
  Clock,
  Zap,
  CheckCircle2,
  Calendar,
  ChevronDown,
  ChevronUp,
  Activity
} from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell
} from "recharts";

interface ProgressAnalyticsViewProps {
  isDarkMode: boolean;
}

export function ProgressAnalyticsView({ isDarkMode }: ProgressAnalyticsViewProps) {
  const [showYearHeatmap, setShowYearHeatmap] = useState(false);
  const [selectedYear, setSelectedYear] = useState("2026");

  const studyHoursData = [
    { day: "Mon", hours: 4.5, target: 4.0 },
    { day: "Tue", hours: 5.2, target: 4.0 },
    { day: "Wed", hours: 3.8, target: 4.0 },
    { day: "Thu", hours: 6.0, target: 4.0 },
    { day: "Fri", hours: 4.0, target: 4.0 },
    { day: "Sat", hours: 7.5, target: 5.0 },
    { day: "Sun", hours: 5.0, target: 5.0 }
  ];

  const focusScoreData = [
    { week: "Week 1", score: 65, retention: 70 },
    { week: "Week 2", score: 72, retention: 78 },
    { week: "Week 3", score: 81, retention: 84 },
    { week: "Week 4", score: 88, retention: 91 }
  ];

  // 30-day activity grid
  const activityDays = Array.from({ length: 30 }, (_, i) => ({
    day: i + 1,
    intensity: ((i * 7 + 3) % 4) + 1
  }));

  // 365-day activity grid generator (52 weeks)
  const fullYearDays = Array.from({ length: 365 }, (_, i) => {
    // Generate deterministic pattern of active vs inactive
    const isActive = (i * 13 + 5) % 10 < 8; // 80% active
    const level = isActive ? ((i % 4) + 1) : 0;
    return { dayIndex: i + 1, level };
  });

  const getIntensityColor = (level: number) => {
    switch (level) {
      case 0: return "bg-slate-900 border-slate-800 opacity-40";
      case 1: return "bg-cyan-950 border-cyan-900";
      case 2: return "bg-cyan-800/60 border-cyan-700";
      case 3: return "bg-cyan-600 border-cyan-500";
      case 4: return "bg-cyan-400 border-cyan-300 shadow-sm";
      default: return "bg-slate-800";
    }
  };

  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Header Banner */}
      <div className={`p-6 rounded-3xl border flex items-center justify-between ${
        isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
      }`}>
        <div className="flex items-center space-x-3">
          <div className="p-3 rounded-2xl bg-gradient-to-tr from-indigo-600 to-blue-500 text-white shadow-lg">
            <BarChart3 className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-black text-white">Student Progress Analytics</h2>
            <p className="text-xs text-slate-400">
              Generated by Progress Analysis Agent &bull; Velocity, retention scores & activity heatmaps
            </p>
          </div>
        </div>
      </div>

      {/* Recharts Charts Row 1 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Study Hours Bar Chart */}
        <div className={`p-6 rounded-3xl border space-y-4 ${
          isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
        }`}>
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <h3 className="font-extrabold text-base text-white flex items-center space-x-2">
              <Clock className="w-4 h-4 text-cyan-400" />
              <span>Daily Study Hours vs Target</span>
            </h3>
            <span className="text-xs font-bold text-cyan-400">Avg: 5.1 hrs/day</span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={studyHoursData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis dataKey="day" stroke="#94a3b8" fontSize={12} />
                <YAxis stroke="#94a3b8" fontSize={12} />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: '12px', color: '#f8fafc' }} />
                <Bar dataKey="hours" fill="#06b6d4" radius={[6, 6, 0, 0]} name="Hours Studied" />
                <Bar dataKey="target" fill="#3b82f6" opacity={0.4} radius={[6, 6, 0, 0]} name="Target Hours" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Focus Score Line Chart */}
        <div className={`p-6 rounded-3xl border space-y-4 ${
          isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
        }`}>
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <h3 className="font-extrabold text-base text-white flex items-center space-x-2">
              <TrendingUp className="w-4 h-4 text-emerald-400" />
              <span>Focus Index & Memory Retention (%)</span>
            </h3>
            <span className="text-xs font-bold text-emerald-400">Peak: 91% Retention</span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={focusScoreData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis dataKey="week" stroke="#94a3b8" fontSize={12} />
                <YAxis stroke="#94a3b8" fontSize={12} />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: '12px', color: '#f8fafc' }} />
                <Line type="monotone" dataKey="score" stroke="#10b981" strokeWidth={3} name="Focus Score" />
                <Line type="monotone" dataKey="retention" stroke="#a855f7" strokeWidth={3} name="Active Recall Retention" />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>

      {/* GitHub-Style Activity Heatmap Grid (30-Day) */}
      <div className={`p-6 rounded-3xl border space-y-4 ${
        isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
      }`}>
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2">
            <Zap className="w-5 h-5 text-amber-400" />
            <h3 className="font-extrabold text-base text-white">30-Day Consistency Activity Heatmap</h3>
          </div>
          <span className="text-xs text-slate-400 font-bold">28 Active Days</span>
        </div>

        <div className="flex flex-wrap gap-2 pt-2">
          {activityDays.map((d) => (
            <div
              key={d.day}
              className={`w-8 h-8 rounded-lg border flex items-center justify-center font-bold text-[10px] text-white transition-all hover:scale-110 ${getIntensityColor(d.intensity)}`}
              title={`Day ${d.day}: Level ${d.intensity} Activity`}
            >
              {d.day}
            </div>
          ))}
        </div>
      </div>

      {/* Dropdown Section: Whole Year (365-Day) Active & Inactive Heatmap */}
      <div className={`p-6 rounded-3xl border space-y-4 transition-all ${
        isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
      }`}>
        <button
          onClick={() => setShowYearHeatmap(!showYearHeatmap)}
          className="w-full flex items-center justify-between font-extrabold text-base text-white focus:outline-none group"
        >
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-cyan-500/20 text-cyan-300">
              <Activity className="w-5 h-5" />
            </div>
            <div className="text-left">
              <span className="block text-base font-extrabold">Whole Year (365-Day) Active & Inactive Dates Heatmap</span>
              <span className="block text-xs text-slate-400 font-normal">
                Click to expand yearly consistency breakdown, active streaks & rest days
              </span>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            <span className="px-3 py-1 rounded-xl bg-slate-800 text-cyan-300 text-xs font-bold border border-slate-700">
              {showYearHeatmap ? "Hide Yearly View" : "Show Full Year Grid"}
            </span>
            {showYearHeatmap ? <ChevronUp className="w-5 h-5 text-cyan-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
          </div>
        </button>

        {showYearHeatmap && (
          <div className="pt-4 border-t border-slate-800 space-y-4 animate-fade-in">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
              <div className="flex items-center space-x-2">
                <span className="text-slate-400 font-bold">Select Year:</span>
                <select
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(e.target.value)}
                  className="px-3 py-1.5 rounded-xl bg-slate-800 border border-slate-700 text-xs text-white font-bold"
                >
                  <option value="2026">2026 Academic Year</option>
                  <option value="2025">2025 Academic Year</option>
                </select>
              </div>

              {/* Legend */}
              <div className="flex items-center space-x-2 text-[11px] text-slate-400">
                <span>Inactive:</span>
                <div className="w-3 h-3 rounded bg-slate-900 border border-slate-800 opacity-40" />
                <span>Low:</span>
                <div className="w-3 h-3 rounded bg-cyan-950 border border-cyan-900" />
                <div className="w-3 h-3 rounded bg-cyan-800/60 border border-cyan-700" />
                <div className="w-3 h-3 rounded bg-cyan-600 border border-cyan-500" />
                <span>High:</span>
                <div className="w-3 h-3 rounded bg-cyan-400 border border-cyan-300" />
              </div>
            </div>

            {/* Month labels */}
            <div className="grid grid-cols-12 gap-1 text-[10px] text-slate-400 font-bold text-center border-b border-slate-800 pb-1">
              {months.map(m => <div key={m}>{m}</div>)}
            </div>

            {/* 365-day grid */}
            <div className="grid grid-flow-col grid-rows-7 gap-1 overflow-x-auto pb-2 scrollbar-none">
              {fullYearDays.map((d) => (
                <div
                  key={d.dayIndex}
                  className={`w-3 h-3 rounded-sm border ${getIntensityColor(d.level)} transition-all hover:scale-125 cursor-pointer`}
                  title={`Day ${d.dayIndex} of ${selectedYear}: ${d.level > 0 ? `Level ${d.level} Activity` : 'Rest / Inactive Day'}`}
                />
              ))}
            </div>

            <div className="flex items-center justify-between text-xs text-slate-400 pt-2 border-t border-slate-800/80">
              <span>Total Active Study Days in {selectedYear}: <strong className="text-cyan-400">292 / 365 Days (80%)</strong></span>
              <span>Longest Continuous Streak: <strong className="text-emerald-400">42 Days</strong></span>
            </div>
          </div>
        )}
      </div>

    </div>
  );
}

