"use client";

import React, { useState } from "react";
import {
  FileSpreadsheet,
  Download,
  Share2,
  Sparkles,
  TrendingUp,
  AlertTriangle,
  CheckCircle2,
  Brain,
  Calendar
} from "lucide-react";
import { WeeklyReport } from "@/lib/student-types";

interface WeeklyReportsViewProps {
  report: WeeklyReport;
  isDarkMode: boolean;
}

export function WeeklyReportsView({ report, isDarkMode }: WeeklyReportsViewProps) {
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleExportCsv = () => {
    const csvContent = [
      ["Metric", "Value"],
      ["Week Range", `"${report.weekRange}"`],
      ["Completion Rate (%)", report.completionRatePercent],
      ["Total Hours Studied", report.totalHoursStudied],
      ["Tasks Completed", report.tasksCompleted],
      ["Strengths", `"${report.strengths.join('; ')}"`],
      ["Weaknesses", `"${report.weaknesses.join('; ')}"`],
      ["Next Week Strategy", `"${report.nextWeekStrategy.replace(/"/g, '""')}"`]
    ].map(r => r.join(",")).join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `weekly_report_${report.weekRange.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Header Banner */}
      <div className={`p-6 rounded-3xl border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 ${
        isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"
      }`}>
        <div className="flex items-center space-x-3">
          <div className="p-3 rounded-2xl bg-gradient-to-tr from-rose-500 to-pink-500 text-white shadow-lg">
            <FileSpreadsheet className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-black text-white">Automated Sunday Reflection Report</h2>
            <p className="text-xs text-slate-400">
              Week of {report.weekRange} &bull; Generated by Progress & Reflection Agents
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleExportCsv}
            className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white font-extrabold text-xs flex items-center space-x-1.5 shadow-lg transition-all"
          >
            <Download className="w-4 h-4" />
            <span>{downloadSuccess ? "Report Downloaded!" : "Export CSV Report"}</span>
          </button>
        </div>
      </div>

      {/* Top Stat Summary Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className={`p-5 rounded-2xl border ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
          <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block">Goal Completion Velocity</span>
          <h3 className="text-2xl font-black text-emerald-400 mt-1">{report.completionRatePercent}%</h3>
          <p className="text-xs text-slate-400 mt-0.5">{report.tasksCompleted} Tasks Completed</p>
        </div>

        <div className={`p-5 rounded-2xl border ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
          <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block">Total Study Time</span>
          <h3 className="text-2xl font-black text-cyan-400 mt-1">{report.totalHoursStudied} Hours</h3>
          <p className="text-xs text-slate-400 mt-0.5">Average 5.2 hrs/day</p>
        </div>

        <div className={`p-5 rounded-2xl border ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
          <span className="text-xs text-slate-400 font-bold uppercase tracking-wider block">Agent Reflection Note</span>
          <p className="text-xs text-slate-300 font-medium mt-1 line-clamp-2">
            &quot;{report.agentReflectionNote}&quot;
          </p>
        </div>
      </div>

      {/* Strengths & Weaknesses Detailed Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Strengths */}
        <div className={`p-6 rounded-3xl border space-y-4 ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
          <div className="flex items-center space-x-2 border-b border-slate-800 pb-3">
            <CheckCircle2 className="w-5 h-5 text-emerald-400" />
            <h3 className="font-extrabold text-base text-white">Strengths & Achievements</h3>
          </div>
          <div className="space-y-2">
            {report.strengths.map((str, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-emerald-950/30 border border-emerald-500/30 text-xs text-emerald-200 font-medium flex items-center space-x-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
                <span>{str}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Weaknesses & Gaps */}
        <div className={`p-6 rounded-3xl border space-y-4 ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
          <div className="flex items-center space-x-2 border-b border-slate-800 pb-3">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
            <h3 className="font-extrabold text-base text-white">Targeted Skill Gaps</h3>
          </div>
          <div className="space-y-2">
            {report.weaknesses.map((wk, idx) => (
              <div key={idx} className="p-3 rounded-xl bg-amber-950/30 border border-amber-500/30 text-xs text-amber-200 font-medium flex items-center space-x-2">
                <AlertTriangle className="w-4 h-4 text-amber-400 flex-shrink-0" />
                <span>{wk}</span>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Actionable Strategy for Next Week */}
      <div className={`p-6 rounded-3xl border space-y-3 ${isDarkMode ? "bg-slate-900 border-slate-800" : "bg-white border-slate-200"}`}>
        <div className="flex items-center space-x-2 border-b border-slate-800 pb-3">
          <Sparkles className="w-5 h-5 text-cyan-400" />
          <h3 className="font-extrabold text-base text-white">Next Week Strategy & Agent Directives</h3>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          {report.nextWeekStrategy}
        </p>
      </div>

    </div>
  );
}
